author:
  name: Joaquin Borrego Fernandez
  email: juakylc14@gmail.com

themoviedb:
  api: 
    key: TU-API-KEY
    
spring:
  application:
    name: watchlist

  #DB Config
  datasource:
    url: ${db:jdbc:mysql://localhost:3306/watchlist?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    #${db:jdbc:postgresql://192.168.1.170:5432/watchlist_su2u?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory}
    username: ${user:root}
    password: ${pass:root}

  jpa:
    hibernate:
      ddl-auto: validate

    defer-datasource-initialization:  true
    #database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql = false
  sql:
    init:
      data-locations:
      - classpath:db/mysql/schema.sql
      - classpath:db/mysql/data.sql
      #La siguiente propiedad indica cuando crear la base de datos. Si está en always la crea siempre, si está en never nunca.
      mode: ${dbinitmode:always}

#Swagger config
springdoc:
  swagger-ui: 
    path: /doc

logging:
  level:
    root: ERROR
    com:
      vedruna:
        watchlist: TRACE
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
